from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
if 'const DP_AUDIO' in s:
    raise SystemExit(0)
patch=r'''
<style>
.audio{width:100%;margin:14px 0}.shop{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.shopItem{padding:15px;border:1px solid var(--line);border-radius:15px;background:#07172a}.shopItem.owned{border-color:#2071a8}.locked{opacity:.55}.tag{font-size:11px;color:#78cdfc}.profilePreview{padding:25px;border-radius:18px;border:1px solid var(--line);min-height:150px;display:flex;align-items:center;gap:18px;background:#07172a}.bigAvatar{width:78px;height:78px;border-radius:24px;display:grid;place-items:center;font-size:30px;font-weight:1000;background:linear-gradient(135deg,var(--blue),#164f9d)}.font-neon{font-family:Impact,Haettenschweiler,'Arial Narrow Bold',sans-serif}.font-mono{font-family:ui-monospace,SFMono-Regular,monospace}.bg-space{background:radial-gradient(circle at 70% 20%,#3153a5,#080b20 45%,#02040b)}.bg-grid{background-image:linear-gradient(#1b4165 1px,transparent 1px),linear-gradient(90deg,#1b4165 1px,transparent 1px);background-size:22px 22px}.bg-purple{background:radial-gradient(circle at 20% 20%,#5b2ca0,#11132e 45%,#05050c)}
@media(max-width:680px){.shop{grid-template-columns:1fr}}
</style>
<script>
const DP_AUDIO={"Skåne":"skane","Blekinge":"blekinge","Södra Halland":"sodra-halland","Södra Småland":"sodra-smaland","Bohuslän":"bohuslan","Dalsland":"dalsland","Göteborg":"goteborg","Norra Halland":"norra-halland","Norra Småland":"norra-smaland","Värmland":"varmland","Västergötland":"vastergotland","Gotländska mål":"gotland","Hälsingland":"halsingland","Härjedalen":"harjedalen","Jämtland":"jamtland","Lappland":"lappland","Medelpad":"medelpad","Norrbotten":"norrbotten","Västerbotten":"vasterbotten","Ångermanland":"angermanland","Bergslagsmål":"bergslagsmal","Dalarna":"dalarna","Gästrikland":"gastrikland","Närke":"narke","Södermanland":"sodermanland","Uppland":"uppland","Västmanland":"vastmanland","Östergötland":"ostergotland","Öland":"oland"};
const DP_REWARDS=[[1,"Startprofil","Gratis"],[2,"🟦 Blå neon","Bakgrund"],[3,"✦ Stjärnavatar","Avatar"],[4,"🟪 Lila space","Bakgrund"],[5,"⚡ Neontext","Textstil"],[6,"🟩 Grid","Bakgrund"],[7,"🎧 Audio Master","Profilbadge"],[8,"🔷 Cyan avatar","Avatar"],[9,"⌘ Mono","Textstil"],[10,"🔥 Streak-profil","Profilbadge"],[12,"🌌 Deep Space","Bakgrund"],[15,"👑 Elite","Avatar"],[20,"💎 DialektLegend","Profilbadge"]];
const DP_SHOP=[{id:'bg-blue',name:'Blue Neon',type:'Bakgrund',cost:120,level:2,cls:''},{id:'bg-purple',name:'Purple Space',type:'Bakgrund',cost:180,level:4,cls:'bg-purple'},{id:'bg-grid',name:'Cyber Grid',type:'Bakgrund',cost:240,level:6,cls:'bg-grid'},{id:'bg-space',name:'Deep Space',type:'Bakgrund',cost:350,level:12,cls:'bg-space'},{id:'font-neon',name:'Neontext',type:'Textstil',cost:160,level:5,cls:'font-neon'},{id:'font-mono',name:'Mono',type:'Textstil',cost:220,level:9,cls:'font-mono'},{id:'avatar-cyan',name:'Cyan Avatar',type:'Avatar',cost:140,level:8,cls:''},{id:'avatar-elite',name:'Elite Avatar',type:'Avatar',cost:450,level:15,cls:''}];
function dpLoad(){return JSON.parse(localStorage.getItem('dialektplay')||'null')||{xp:0,answered:0,correct:0,streak:0,coins:0,name:'SimSim',owned:['start'],bg:'',font:'',avatar:'default',badges:[]}}
let DP=dpLoad();
function dpLevel(){return Math.floor(DP.xp/100)+1}function dpSave(){localStorage.setItem('dialektplay',JSON.stringify(DP));document.getElementById('xp').textContent=DP.xp;document.getElementById('level').textContent=dpLevel();if(document.getElementById('coins'))document.getElementById('coins').textContent=DP.coins;document.getElementById('topAvatar').textContent=DP.avatar==='avatar-elite'?'👑':DP.avatar==='avatar-cyan'?'✦':'S'}function dpGain(x,c){let old=dpLevel();DP.xp+=x;DP.coins+=c;dpSave();if(dpLevel()>old){document.getElementById('modalBody').innerHTML='<h1>🎉 Nivå '+dpLevel()+'!</h1><p>Du har låst upp nya saker i ditt <b>XP Pass</b>.</p><button class="btn primary" onclick="closeModal();showProfile()">Öppna XP Pass</button>';document.getElementById('modal').classList.add('show')}}
function dpAudio(slug){return '<audio class="audio" controls preload="metadata"><source src="audio/'+slug+'.mp3" type="audio/mpeg"></audio><p class="muted">🎧 DialektPlay · cirka 15 sekunder</p>'}function dpPlay(){setTimeout(()=>document.querySelector('#modalBody audio')?.play().catch(()=>{}),180)}
let DPQ=[],DPQI=0;function startQuiz(){active(1);DPQ=DIALECTS.slice().sort(()=>Math.random()-.5).slice(0,10);DPQI=0;dpQuiz()}function dpQuiz(){let q=DPQ[DPQI],o=[q[0],...DIALECTS.filter(x=>x[0]!==q[0]).sort(()=>Math.random()-.5).slice(0,3).map(x=>x[0])].sort(()=>Math.random()-.5);document.getElementById('modalBody').innerHTML='<p class="muted">Fråga '+(DPQI+1)+' av 10</p><h2>🎧 Vilken dialekt hör du?</h2>'+dpAudio(DP_AUDIO[q[0]])+'<div class="quiz-options">'+o.map(x=>'<button class="answer" onclick="dpAnswer(this,'+JSON.stringify(x)+','+JSON.stringify(q[0])+')">'+x+'</button>').join('')+'</div><div id="quizFeedback"></div>';document.getElementById('modal').classList.add('show');dpPlay()}function dpAnswer(b,a,r){if(b.dataset.done)return;b.dataset.done=1;DP.answered++;if(a===r){b.classList.add('correct');DP.correct++;DP.streak++;dpGain(20,12);document.getElementById('quizFeedback').textContent='✅ Rätt! +20 XP och +12 🪙'}else{b.classList.add('wrong');DP.streak=0;dpSave();document.getElementById('quizFeedback').textContent='❌ Rätt svar: '+r}setTimeout(()=>{DPQI++;DPQI<10?dpQuiz():(closeModal(),showHome())},900)}
function showGames(){active(2);page('Spel','<h1>Minigames</h1><p class="muted">Alla spel använder DialektPlay-ljud.</p><div class="grid"><div class="card"><h2>⚡ Speed Audio</h2><p>Hör ett klipp och svara snabbt.</p><button class="btn primary" onclick="dpSpeed()">Spela</button></div><div class="card"><h2>🎯 Streak</h2><p>Tre ljud rätt i rad.</p><button class="btn primary" onclick="dpStreak()">Spela</button></div></div>')}function dpSpeed(){let q=DIALECTS[Math.floor(Math.random()*DIALECTS.length)],o=[q[0],...DIALECTS.filter(x=>x[0]!==q[0]).sort(()=>Math.random()-.5).slice(0,3).map(x=>x[0])].sort(()=>Math.random()-.5);document.getElementById('modalBody').innerHTML='<h2>⚡ Speed Audio</h2>'+dpAudio(DP_AUDIO[q[0]])+'<div class="quiz-options">'+o.map(x=>'<button class="answer" onclick="dpGameAnswer(this,'+JSON.stringify(x)+','+JSON.stringify(q[0])+')">'+x+'</button>').join('')+'</div><div id="gameFeedback"></div>';document.getElementById('modal').classList.add('show');dpPlay()}function dpGameAnswer(b,a,r){if(b.dataset.done)return;b.dataset.done=1;if(a===r){b.classList.add('correct');dpGain(10,6);document.getElementById('gameFeedback').textContent='✅ Rätt! +10 XP och +6 🪙'}else{b.classList.add('wrong');document.getElementById('gameFeedback').textContent='❌ Rätt svar: '+r}}function dpStreak(){dpSpeed()}
function showDialects(){active(3);page('Dialekter','<h1>Dialektområden</h1><p class="muted">Varje område har ett eget DialektPlay-klipp.</p><input id="dialectSearch" class="search" placeholder="🔎 Sök dialektområde..." oninput="filterDialects()"><div id="dialectList" class="dialects">'+DIALECTS.map((d,i)=>'<article class="dialect"><span class="pill">'+d[1]+'</span><h3>'+d[0]+'</h3><button class="btn primary" onclick="openDialect('+i+')">🎧 Lyssna</button></article>').join('')+'</div>')}function openDialect(i){let d=DIALECTS[i];document.getElementById('modalBody').innerHTML='<span class="pill">'+d[1]+'</span><h2>'+d[0]+'</h2><p>Eget DialektPlay-övningsklipp, cirka 15 sekunder.</p>'+dpAudio(DP_AUDIO[d[0]])+'<div class="notice">💡 Samma ljud används i quizet.</div>';document.getElementById('modal').classList.add('show')}
function showProfile(){active(6);page('Profil','<h1>👤 Din profil</h1><div class="profilePreview '+DP.font+' '+DP.bg+'"><div class="bigAvatar">'+(DP.avatar==='avatar-elite'?'👑':DP.avatar==='avatar-cyan'?'✦':'S')+'</div><div><h2>'+DP.name+'</h2><p class="muted">Nivå '+dpLevel()+' · '+DP.xp+' XP · '+DP.coins+' 🪙</p><span class="pill">XP Pass</span></div></div><div class="card" style="margin-top:12px"><h2>🎟️ XP Pass</h2><p class="muted">Levla upp och lås upp profilgrejer. Inga riktiga pengar.</p><div class="progress"><i style="width:'+(DP.xp%100)+'%"></i></div><div class="list" style="margin-top:12px">'+DP_REWARDS.map(r=>'<div class="row '+(dpLevel()>=r[0]?'':'locked')+'"><b>Nivå '+r[0]+' · '+r[1]+'</b><span>'+(dpLevel()>=r[0]?'🔓':'🔒')+'</span></div>').join('')+'</div></div><div class="card" style="margin-top:12px"><h2>🛍️ Profilshop</h2><p class="muted">Du tjänar 🪙 när du spelar.</p><div class="shop">'+DP_SHOP.map(x=>{let own=DP.owned.includes(x.id),can=dpLevel()>=x.level;return '<div class="shopItem '+(own?'owned ':'')+(!can?'locked':'')+'"><span class="tag">'+x.type+' · nivå '+x.level+'</span><h3>'+x.name+'</h3><p>'+x.cost+' 🪙</p>'+(own?'<button class="btn" onclick="dpEquip('+JSON.stringify(x.id)+')">Använd</button>':can?'<button class="btn primary" onclick="dpBuy('+JSON.stringify(x.id)+')">Köp</button>':'<button class="btn" disabled>🔒 Låst</button>')+'</div>'}).join('')+'</div></div>')}
function dpBuy(id){let x=DP_SHOP.find(s=>s.id===id);if(!x||DP.owned.includes(id)||dpLevel()<x.level||DP.coins<x.cost)return;DP.coins-=x.cost;DP.owned.push(id);dpSave();showProfile()}function dpEquip(id){let x=DP_SHOP.find(s=>s.id===id);if(!x)return;if(x.type==='Bakgrund')DP.bg=x.cls;if(x.type==='Textstil')DP.font=x.cls;if(x.type==='Avatar')DP.avatar=id;document.body.className=DP.font+' '+DP.bg;dpSave();showProfile()}function dpBoot(){let nav=document.querySelector('.nav');if(nav&&!document.getElementById('n6')){let b=document.createElement('button');b.id='n6';b.textContent='👤 Profil';b.onclick=showProfile;nav.appendChild(b)}let top=document.querySelector('.user small');if(top&&!document.getElementById('coins'))top.innerHTML=top.innerHTML.replace('</span> XP','</span> XP · <span id="coins">0</span> 🪙');DP=dpLoad();document.body.className=DP.font+' '+DP.bg;dpSave()}dpBoot();
</script>
'''
s=s.replace('</body>',patch+'</body>')
p.write_text(s,encoding='utf-8')
